# Generated by Django 4.1.5 on 2023-01-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='description',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Обозначение'),
        ),
    ]
