# Generated by Django 4.1.5 on 2023-01-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_code', '0002_alter_code_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='children',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='search_code.code', verbose_name='Ребёнок'),
        ),
    ]
